version: '2'
services:
  dbtest:
    image: mariadb:5
    volumes:
    - dbtest_data:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=toweltest
    - MYSQL_ROOT_PASSWORD=root
  database:
    image: mariadb:5
    volumes:
    - database_data:/var/lib/mysql
    ports:
    - 4242:3306
    environment:
    - MYSQL_DATABASE=towel
    - MYSQL_ROOT_PASSWORD=root
  php:
    image: fcoedno/php:7.1-fpm-symfony-dev
    volumes:
      - ./:/code
      - composercache:/.composer
    working_dir: /code
    environment:
    - USER_ID=${UID}
    - SYMFONY__DB__NAME=towel
    - SYMFONY__DB__PASSWORD=root
    - SYMFONY__DB__USER=root
    - SYMFONY__DB__PORT=3306
    - SYMFONY__DB__HOST=database
    - SYMFONY__DB__TEST__NAME=toweltest
    - SYMFONY__DB__TEST__PASSWORD=root
    - SYMFONY__DB__TEST__USER=root
    - SYMFONY__DB__TEST__PORT=3306
    - SYMFONY__DB__TEST__HOST=dbtest
    user: ${UID}
  web:
    image: fcoedno/nginx:1.13.8-symfony-dev
    volumes:
    - ./:/code:ro
    depends_on:
    - php
    ports:
    - 80:80
    environment:
    - NGINX_HOST=towel.localhost
volumes:
  database_data:
  dbtest_data:
  composercache:
