# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  # Repositories
  repository.person_repository:
    class: AppBundle\Repository\DoctrinePersonRepository
    arguments: ['@doctrine.orm.entity_manager']
  repository.order_repository:
    class: AppBundle\Repository\DoctrineOrderRepository
    arguments: ['@doctrine.orm.entity_manager']

  # Controllers
  http.api.order.index_action:
    class: AppBundle\Http\Api\Order\IndexAction
    arguments: ['@repository.order_repository', '@jms_serializer.serializer']
  http.api.order.details_action:
    class: AppBundle\Http\Api\Order\DetailsAction
    arguments: ['@repository.order_repository', '@jms_serializer.serializer']
  http.api.person.index_action:
    class: AppBundle\Http\Api\Person\IndexAction
    arguments: ['@repository.person_repository', '@jms_serializer.serializer']
  http.api.person.details_action:
    class: AppBundle\Http\Api\Person\DetailsAction
    arguments: ['@repository.person_repository', '@jms_serializer.serializer']

  # Service - Importer
  service.file_importer.factory:
    class: AppBundle\Service\FileImporter\Factory\XmlFileImporterFactory
    autowire: true
  service.importer.xml_importer.person_importer:
    class: AppBundle\Service\Importer\XmlImporter\PersonImporter
    autowire: true
  service.importer.xml_importer.order_importer:
    class: AppBundle\Service\Importer\XmlImporter\OrderImporter
    autowire: true
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
